### ISSUE TITLE
Bug: using rust style comments on unicode breaks the comment sintax 

### ISSUE THREAD

**Issue by jvlara** [rszyma/vscode-kanata#37]
Hi, i was looking to do a " in unicode with this [PR](https://github.com/jtroo/kanata/pull/1021)

It all works well but the sintax is breaking
![image](https://github.com/user-attachments/assets/fc0ea764-bc64-4dae-9072-5f99d537d8af)

it seems that it does not detect that the string ended

**Comment by rszyma** [comment]
fixed in 77da3f180290ad2b6821fedc4c7697f7c0dd49fc

**Comment by jvlara** [comment]
thanks! <3
