### ISSUE TITLE
Consider publishing to Open VSX

### ISSUE THREAD

**Issue by fnuttens** [rszyma/vscode-kanata#38]
Publishing the extension on [open-vsx.org](https://open-vsx.org) would make it available on editors like [VSCodium](https://vscodium.com/).

**Comment by rszyma** [comment]
done
5dc8f1592eae9b25c37f69b77441207551e57a56
https://open-vsx.org/extension/rszyma/vscode-kanata

**Comment by fnuttens** [comment]
Thank you!
